# Generated by Django 6.1.1 on 2026-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='highlights', to='content.story'),
        ),
    ]
